#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ln -sf $DIR/.bashrc_dispatch ~/.bashrc
ln -sf $DIR/.bashrc_dispatch ~/.bash_profile
ln -sf $DIR/.bashrc_dispatch ~/.profile
ln -sf $DIR/.bashrc_dispatch ~/.bash_login

ln -sf $DIR/.bashrc_all ~/.bashrc_all
ln -sf $DIR/.bashrc_script ~/.bashrc_script
ln -sf $DIR/.bashrc_interactive ~/.bashrc_interactive
ln -sf $DIR/.bashrc_login ~/.bashrc_login

rm -rf ~/.vim
ln -sf $DIR/.vim ~/.vim
ln -sf $DIR/.vimrc ~/.vimrc

rm -rf $DIR/.vim/bundle
mkdir -p $DIR/.vim/bundle
curl -fLo $DIR/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

open /Users/AdilSoubki/.dotfiles/.terminal/Molokai.terminal

