#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ln -sf $DIR/.bashrc_dispatch ~/.bashrc
ln -sf $DIR/.bashrc_dispatch ~/.bash_profile
ln -sf $DIR/.bashrc_dispatch ~/.profile
ln -sf $DIR/.bashrc_dispatch ~/.bash_login

ln -sf $DIR/.bashrc_all ~/.bashrc_all
ln -sf $DIR/.bashrc_script ~/.bashrc_script
ln -sf $DIR/.bashrc_interactive ~/.bashrc_interactive
ln -sf $DIR/.bashrc_login ~/.bashrc_login

rm -rf ~/.vim
ln -sf $DIR/.vim ~/.vim
ln -sf $DIR/.vimrc ~/.vimrc

rm -rf $DIR/.vim/bundle
mkdir -p $DIR/.vim/bundle
cd $DIR/.vim/bundle
git clone git://github.com/tpope/vim-sensible.git
git clone https://github.com/flazz/vim-colorschemes.git

open /Users/AdilSoubki/.dotfiles/.terminal/Molokai.terminal

